//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StarTrayTemperature.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UseFahrenheit {
            get {
                return ((bool)(this["UseFahrenheit"]));
            }
            set {
                this["UseFahrenheit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowCPU {
            get {
                return ((bool)(this["ShowCPU"]));
            }
            set {
                this["ShowCPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowGPU {
            get {
                return ((bool)(this["ShowGPU"]));
            }
            set {
                this["ShowGPU"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool PawnIODeclined {
            get {
                return ((bool)(this["PawnIODeclined"]));
            }
            set {
                this["PawnIODeclined"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GPU_SelectedName {
            get {
                return ((string)(this["GPU_SelectedName"]));
            }
            set {
                this["GPU_SelectedName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CPU_HoverShowTemperature {
            get {
                return ((bool)(this["CPU_HoverShowTemperature"]));
            }
            set {
                this["CPU_HoverShowTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CPU_HoverShowLoad {
            get {
                return ((bool)(this["CPU_HoverShowLoad"]));
            }
            set {
                this["CPU_HoverShowLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CPU_HoverShowPower {
            get {
                return ((bool)(this["CPU_HoverShowPower"]));
            }
            set {
                this["CPU_HoverShowPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CPU_HoverShowClock {
            get {
                return ((bool)(this["CPU_HoverShowClock"]));
            }
            set {
                this["CPU_HoverShowClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool GPU_HoverShowTemperature {
            get {
                return ((bool)(this["GPU_HoverShowTemperature"]));
            }
            set {
                this["GPU_HoverShowTemperature"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GPU_HoverShowLoad {
            get {
                return ((bool)(this["GPU_HoverShowLoad"]));
            }
            set {
                this["GPU_HoverShowLoad"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GPU_HoverShowPower {
            get {
                return ((bool)(this["GPU_HoverShowPower"]));
            }
            set {
                this["GPU_HoverShowPower"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GPU_HoverShowClock {
            get {
                return ((bool)(this["GPU_HoverShowClock"]));
            }
            set {
                this["GPU_HoverShowClock"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool GPU_HoverShowMemory {
            get {
                return ((bool)(this["GPU_HoverShowMemory"]));
            }
            set {
                this["GPU_HoverShowMemory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CPU_IconColor1 {
            get {
                return ((global::System.Drawing.Color)(this["CPU_IconColor1"]));
            }
            set {
                this["CPU_IconColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CPU_IconColor2 {
            get {
                return ((global::System.Drawing.Color)(this["CPU_IconColor2"]));
            }
            set {
                this["CPU_IconColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color CPU_TextColor {
            get {
                return ((global::System.Drawing.Color)(this["CPU_TextColor"]));
            }
            set {
                this["CPU_TextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color GPU_IconColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GPU_IconColor1"]));
            }
            set {
                this["GPU_IconColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color GPU_IconColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GPU_IconColor2"]));
            }
            set {
                this["GPU_IconColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Drawing.Color GPU_TextColor {
            get {
                return ((global::System.Drawing.Color)(this["GPU_TextColor"]));
            }
            set {
                this["GPU_TextColor"] = value;
            }
        }
    }
}
